// Code generated by clientgen; DO NOT EDIT.
package client

type WEBGL_draw_instanced_base_vertex_base_instanceType struct{}

func (WEBGL_draw_instanced_base_vertex_base_instanceType) clientType() {}
