// Code generated by clientgen; DO NOT EDIT.
package client

type MAX_HANDLER_BEHAVIOR_CHANGED_CALLS_PER_10_MINUTESType struct{}

func (MAX_HANDLER_BEHAVIOR_CHANGED_CALLS_PER_10_MINUTESType) clientType() {}
