package client

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type generatedRecord struct {
	ID, Name, Kind string
	Members        []struct {
		Name, Kind string
		Type       *struct {
			Name, Ref string
			Nullable  bool
		} `json:"type"`
		Signatures []struct {
			Inputs []struct {
				Name string
				Type struct {
					Name, Ref string
					Nullable  bool
				} `json:"type"`
			}
			Output *struct {
				Name, Ref string
				Nullable  bool
			}
		}
	} `json:"members"`
}

func GenerateBindings(root, output string, check bool) error {
	var records []generatedRecord
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, e error) error {
		if e != nil {
			return e
		}
		if d.IsDir() || d.Name() != "index.json" {
			return nil
		}
		b, e := os.ReadFile(path)
		if e != nil {
			return e
		}
		var r generatedRecord
		if e = json.Unmarshal(b, &r); e != nil {
			return e
		}
		if r.Name != "" {
			records = append(records, r)
		}
		return nil
	})
	if err != nil {
		return err
	}
	sort.Slice(records, func(i, j int) bool { return records[i].ID < records[j].ID })
	if !check {
		if e := os.MkdirAll(output, 0755); e != nil {
			return e
		}
	}
	for _, r := range records {
		if r.Kind != "interface" {
			continue
		}
		name := goName(r.Name)
		if name == "String" || name == "Number" || name == "Boolean" || name == "Null" || name == "Undefined" || name == "Unknown" || name == "Element" || name == "Node" || name == "Event" {
			continue
		}
		code := []byte("// Code generated by clientgen; DO NOT EDIT.\npackage browser\n\nimport \"github.com/nsatyasrikar/client\"\n\ntype " + name + "Type struct{ client.TypeMarker }\n")
		formatted, e := format.Source(code)
		if e != nil {
			return e
		}
		path := filepath.Join(output, "browser_"+kebab(r.Name)+".go")
		if check {
			old, _ := os.ReadFile(path)
			if string(old) != string(formatted) {
				return fmt.Errorf("stale generated file %s", path)
			}
		} else {
			if e := os.WriteFile(path, formatted, 0644); e != nil {
				return e
			}
		}
	}
	return nil
}
func goName(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			if upper && r >= 'a' && r <= 'z' { r -= 'a' - 'A' }
			b.WriteRune(r); upper = false
		} else { upper = true }
	}
	name := b.String()
	if name == "" { return "Generated" }
	if name[0] >= '0' && name[0] <= '9' { return "X" + name }
	return name
}
func kebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteByte(byte(r - 'A' + 'a'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
